version: '3.8'

services:
  app:
    image: node:18-bullseye-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - CI_COMMIT_SHA=${CI_COMMIT_SHA}
    volumes:
      - ./:/usr/src/app
    command: npm run dev